const A={
  home:'./assets/brand/home-kamakura-train__hero_16x9.jpg',
  osaka:'./assets/cities/osaka-dotonbori-night__card_4x3.jpg',
  kyoto:'./assets/cities/kyoto-fushimi-inari__card_4x3.jpg',
  fuji:'./assets/cities/fuji-kawaguchiko__card_4x3.jpg',
  tokyo:'./assets/cities/tokyo-tower-night__card_4x3.jpg',
  seoul:'./assets/cities/seoul-myeongdong-evening__card_4x3.jpg',
  veganRamen:'./assets/food/vegan-ramen-ts-tantan__card_4x3.jpg'
};

const state={view:'home'};
const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1700)}
function go(view){state.view=view;render();window.scrollTo({top:0,behavior:'instant'})}
function nav(){return `<nav class="bottom-nav" aria-label="Primary navigation">
<button class="${state.view==='home'?'active':''}" onclick="go('home')"><span>⌂</span><small>Home</small></button>
<button class="${state.view==='journey'?'active':''}" onclick="go('journey')"><span>🚆</span><small>Journey</small></button>
<button class="${state.view==='chapter'?'active':''}" onclick="go('chapter')"><span>▣</span><small>Chapter</small></button>
</nav>`}
function header(){return `<header class="topbar"><div><div class="brand-title">The Sakura <span>&</span> Seoul Journal</div><div class="brand-subtitle">Our Honeymoon Journal</div></div><div class="top-actions"><button class="icon-button" onclick="toast('Notifications will be connected later')">✓</button><button class="icon-button" onclick="go('wallet')">▣</button></div></header>`}
function home(){app.innerHTML=`<main class="app">${header()}
<section class="hero"><img src="${A.home}" alt="Enoden train in Kamakura"><div class="weather-pill"><strong>22°</strong><div>Osaka preview<small>Sunny · feels like 21°</small></div></div><div class="hero-copy"><h1>84 days until our adventure</h1><p>Kamakura train · the beginning of our story</p></div></section>
<section class="card"><div class="section-head"><h2>Trip Readiness</h2><button class="text-button" onclick="go('readiness')">Open →</button></div><div class="readiness-top"><div class="progress-ring" style="--pct:17"><strong>17%</strong></div><div class="readiness-copy"><strong>17% Ready to Go</strong><span>2 of 12 complete</span></div></div><div class="priority"><div class="priority-label">Today's Priority</div><h3>Book Tokyo Disneyland tickets</h3><p>Check the official booking window and current availability.</p><div class="button-row"><button class="primary" onclick="toast('Booking link opens in readiness sprint')">Open</button><button class="secondary" onclick="toast('Marked complete')">Mark complete</button></div></div></section>
<section class="card"><div class="section-head"><h2>Journey Progress</h2><button class="text-button" onclick="go('journey')">View →</button></div><div class="journey-preview"><div class="journey-track"></div><div class="journey-stops"><div class="journey-stop"><div class="dot">✈</div>Toronto</div><div class="journey-stop current"><div class="dot">🐙</div>Osaka</div><div class="journey-stop"><div class="dot">⛩</div>Kyoto</div><div class="journey-stop"><div class="dot">🗻</div>Fuji</div><div class="journey-stop"><div class="dot">🗼</div>Tokyo</div><div class="journey-stop"><div class="dot">▤</div>Seoul</div></div></div></section>
<section class="tile-grid"><button class="tile" onclick="toast('Basecamp will connect in Osaka sprint')"><img src="${A.osaka}" alt="Dotonbori in Osaka"><div class="tile-copy"><strong>Stay</strong><small>Basecamp and check-in</small></div></button><button class="tile" onclick="toast('Taste & Moments will connect in Osaka sprint')"><img src="${A.veganRamen}" alt="Vegan ramen without egg"><div class="tile-copy"><strong>Taste</strong><small>Vegetarian and vegan food</small></div></button><button class="tile" onclick="toast('Explore will connect in Osaka sprint')"><img src="${A.kyoto}" alt="Fushimi Inari torii gates"><div class="tile-copy"><strong>Explore</strong><small>Places and essentials</small></div></button><button class="tile" onclick="go('wallet')"><img src="${A.tokyo}" alt="Tokyo Tower at night"><div class="tile-copy"><strong>Travel Wallet</strong><small>Tickets and documents</small></div></button></section>
<section class="card"><div class="section-head"><h2>Budget Train</h2><span class="muted">58% used</span></div><div class="budget-line"><span class="budget-train">🚃</span></div><div class="budget-meta"><span>Flights</span><span>Stay</span><span>Food</span><span>Shopping</span></div></section>${nav()}</main>`}
function journey(){const cities=[['🐙','Osaka','Oct 7–10 · 3 nights · Next Chapter',A.osaka,'Next Chapter'],['⛩','Kyoto','Oct 10–12 · 2 nights',A.kyoto,''],['🗻','Fuji / Hakone','Oct 12–16 · 4 nights',A.fuji,''],['🗼','Tokyo','Oct 16–21 · 5 nights',A.tokyo,''],['▤','Seoul','Oct 21–25 · 4 nights',A.seoul,'']];app.innerHTML=`<main class="app"><div class="page-title"><button class="back-button" onclick="go('home')">←</button><h1>Our Journey</h1></div><p class="page-intro">Choose a chapter</p><section class="city-list">${cities.map(c=>`<button class="city-card" onclick="toast('${c[1]} dashboard is the next build sprint')"><img src="${c[3]}" alt="${c[1]}">${c[4]?`<span class="status-pill">${c[4]}</span>`:''}<div class="city-card-copy"><strong>${c[0]} ${c[1]}</strong><span>${c[2]}</span></div></button>`).join('')}</section>${nav()}</main>`}
function chapter(){const groups=[['🌅 Morning',[['Coffee first',A.veganRamen,'Vegetarian breakfast or coffee stop'],['Osaka Castle',A.osaka,'Castle grounds and city views']]],['☀️ Afternoon',[['Namba & Shinsaibashi',A.osaka,'Shopping streets and nearby vegetarian food'],['Vegetarian lunch',A.veganRamen,'Egg-free vegetarian or vegan meal']]],['🌇 Evening',[['Dotonbori walk',A.osaka,'Neon lights and canal views'],['Return to basecamp',A.osaka,'Directions back to the Osaka hotel']]]];app.innerHTML=`<main class="app"><div class="page-title"><button class="back-button" onclick="go('home')">←</button><h1>Today's Chapter</h1></div><section class="card"><div class="section-head"><h2>Today's Essentials</h2></div><div class="essentials"><div class="essential-row"><span>☀️</span><div><strong>22° · Weather closer to the trip</strong><small>Forecast will update automatically.</small></div></div><div class="essential-row"><span>🎫</span><div><strong>No JR Pass needed today</strong><small>Use your IC card for local travel.</small></div></div><div class="essential-row"><span>💴</span><div><strong>Carry some cash</strong><small>Useful for markets and small shops.</small></div></div></div></section>${groups.map(g=>`<section class="chapter-section"><h2>${g[0]}</h2>${g[1].map(x=>`<article class="experience"><img src="${x[1]}" alt="${x[0]}"><div><strong>${x[0]}</strong><small>${x[2]}</small></div></article>`).join('')}</section>`).join('')}${nav()}</main>`}
function readiness(){const cats=[['🎟','Bookings','2 of 5 complete','40%'],['📄','Documents','3 of 4 complete','75%'],['🧳','Packing','1 of 12 complete','8%'],['💳','Money','1 of 4 complete','25%'],['📱','Digital','0 of 4 complete','0%'],['🚆','Transport','1 of 4 complete','25%']];app.innerHTML=`<main class="app"><div class="page-title"><button class="back-button" onclick="go('home')">←</button><h1>Trip Readiness</h1></div><section class="card"><div class="section-head"><h2>84 Days Remaining</h2><span class="muted">17% Ready to Go</span></div><div class="mini-progress"><i style="--p:17%"></i></div></section><section class="card"><div class="section-head"><h2>Today's Priority</h2></div><div class="priority"><div class="priority-label">Booking</div><h3>Book Tokyo Disneyland tickets</h3><p>Check the official sale window before availability becomes limited.</p><div class="button-row"><button class="primary" onclick="toast('Official booking link will connect next')">Open</button><button class="secondary" onclick="toast('Marked complete')">Mark complete</button></div></div></section><section class="card"><div class="section-head"><h2>Due Soon</h2><button class="text-button" onclick="toast('Due Soon list will connect next')">View All →</button></div></section><div class="section-head"><h2>Getting Ready</h2></div><section class="category-grid">${cats.map(c=>`<button class="category-card" onclick="toast('${c[1]} checklist opens in readiness sprint')"><div class="icon">${c[0]}</div><strong>${c[1]}</strong><small>${c[2]}</small><div class="mini-progress"><i style="--p:${c[3]}"></i></div></button>`).join('')}</section>${nav()}</main>`}
function wallet(){const comps=[['🛂','Documents','Passport, visa and insurance'],['🎫','Tickets & Passes','Flights, trains and activities'],['🏨','Reservations','Hotels, dining and experiences'],['💳','Payments','Cash, cards and tax-free'],['🚨','Emergency','Contacts and translation cards'],['↓','Downloads','Offline maps and PDFs']];app.innerHTML=`<main class="app"><div class="page-title"><button class="back-button" onclick="go('home')">←</button><h1>Travel Wallet</h1></div><section class="card"><div class="section-head"><h2>Ready Now</h2><button class="text-button" onclick="toast('Upload flow is planned for Wallet sprint')">+ Add</button></div><div class="ready-strip"><div class="ready-item"><strong>🛂 Passport</strong><small>Quick document access</small></div><div class="ready-item"><strong>🏨 Osaka Hotel</strong><small>Oct 7 check-in</small></div><div class="ready-item"><strong>✈ Flight</strong><small>Toronto → Osaka</small></div></div></section><section class="wallet-grid">${comps.map(c=>`<button class="wallet-card" onclick="toast('${c[1]} opens in Wallet sprint')"><div class="icon">${c[0]}</div><strong>${c[1]}</strong><small>${c[2]}</small></button>`).join('')}</section>${nav()}</main>`}
function render(){({home,journey,chapter,readiness,wallet}[state.view]||home)()}
window.go=go;render();
